# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e697b6c87acaa864e7454e7fbf9fb26c0cea294d768f28eadb12ce4c5944a3bfbb9c66900652b043c404eb2fa8b53237f596ca994cf8657824bed61b17da26ac

test:
  secret_key_base: 41a7905d6383c2c829448e2fb20e31ace031437165fe153179e22b28b2deae8cd7e65f9e8c56f0b0ba0e9f53fdfd65402557a35f459049adf0c1f7b1e549b643

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
